#!/bin/bash

### BEGIN INIT INFO
# PUT THIS SCRIPT INSIDE /usr/bin/ AS "USER INTERFACEs"
# Provides:          anonsurf
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:
# Default-Stop:
# Short-Description: Transparent Proxy through TOR.
### END INIT INFO
#
# Devs:
# Lorenzo 'Palinuro' Faletra <palinuro@parrotsec.org>
# Lisetta 'Sheireen' Ferrero <sheireen@autistiche.org>
# Francesco 'Mibofra' Bonanno <mibofra@parrotsec.org>
#
# Maintainer:
# Nong Hoang 'DmKnght' Tu <dmknght@parrotsec.org>
#
# Extended:
# Daniel 'Sawyer' Garcia <dagaba13@gmail.com>
#
# Modified:
# boussad ait salem  <baitsalem@gmail.com>
#
# anonsurf is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# You can get a copy of the license at www.gnu.org/licenses
#
# anonsurf is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Parrot Security OS. If not, see <http://www.gnu.org/licenses/>.


export BLUE='\033[1;94m'
export GREEN='\033[1;92m'
export RED='\033[1;91m'
export RESETCOLOR='\033[1;00m'



function init {
	echo -e -n "$BLUE[$GREEN*$BLUE] killing dangerous applications\n"
	sudo killall -q chrome dropbox iceweasel skype icedove thunderbird firefox firefox-esr chromium xchat hexchat transmission steam firejail
	echo -e -n "$BLUE[$GREEN*$BLUE] Dangerous applications killed\n"

	echo -e -n "$BLUE[$GREEN*$BLUE] cleaning some dangerous cache elements\n"
	bleachbit -c adobe_reader.cache chromium.cache chromium.current_session chromium.history elinks.history emesene.cache epiphany.cache firefox.url_history flash.cache flash.cookies google_chrome.cache google_chrome.history  links2.history opera.cache opera.search_history opera.url_history &> /dev/null
	echo -e -n "$BLUE[$GREEN*$BLUE] Cache cleaned\n"
}


function ip {
	MYIP=`wget -qO- https://start.parrotsec.org/ip/`
	echo -e "\nMy ip is:\n"
	echo $MYIP
	echo -e "\n"
}


function checkuid {
	# Make sure only root can run this script
	ME=$(whoami | tr [:lower:] [:upper:])
	if [ $(id -u) -ne 0 ]; then
		echo -e "\n$GREEN[$RED!$GREEN] $RED $ME R U DRUNK?? This script must be run as root$RESETCOLOR\n" >&2
		exit 1
	fi
}


function start {

	echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Starting anonymous mode:$RESETCOLOR\n"

	systemctl start anonsurfd

	echo -e "$GREEN *$BLUE All traffic was redirected throught Tor\n"
	echo -e "$GREEN[$BLUE i$GREEN ]$BLUE You are under AnonSurf tunnel$RESETCOLOR\n"
	echo -e "Global Anonymous Proxy Activated\n" > /etc/anonsurf/conky_msg
	sleep 4
}


function stop {
	echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Stopping anonymous mode:$RESETCOLOR\n"

	systemctl stop anonsurfd 

	echo -e " $GREEN*$BLUE Anonymous mode stopped\n"
	echo -e "Global Anonymous Proxy Closed - Stop dancing :(\n" > /etc/anonsurf/conky_msg

	sleep 3
}


function enable-boot {
	if [ "$(systemctl list-unit-files | grep anonsurfd | awk '{print $2}')" = "disabled" ]; then
		systemctl enable anonsurfd;
		echo "Enabling AnonSurf at boot"
	else
		echo -e "\n$GREEN[$RED!$GREEN] $RED Anonsurf already enabled!$RESETCOLOR\n"
	fi
}


function disable-boot {
	if [ "$(systemctl list-unit-files | grep anonsurfd | awk '{print $2}')" = "enabled" ]; then
		systemctl enable anonsurfd;
		echo "Disabling AnonSurf at boot"
	else
		echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf wasn't enabled. Nothing to disable!$RESETCOLOR\n"
	fi
}


function change {
	echo -e "authenticate \"kuhNygbtfu76fFUbgv\"\nsignal newnym\nquit" | nc localhost -q 1 9051
	systemctl restart  tor 
	sleep 1
	echo -e " $GREEN*$BLUE Tor daemon reloaded and forced to change nodes\n"
	echo -e "Identity changed - let's dance again!\n" > /etc/anonsurf/conky_msg

	sleep 1
}


function status {
	nyx
}



case "$1" in
	start)
	# Only start if anonsurfd is not running
	# TODO try to run if the service status is failed?
		checkuid
		if [ "$(systemctl is-active anonsurfd)" = "inactive" ]; then
			zenity --question --text="Do you want anonsurf to kill dangerous applications and clean some application caches?" --width 400 && init
			start
		else
			echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is running! Can't start service!$RESETCOLOR\n" >&2
		fi
	;;
	stop)
	# Only stop if the anonsurfd is running
		checkuid
		if [ "$(systemctl is-active anonsurfd)" = "active" ]; then
			zenity --question --text="Do you want anonsurf to kill dangerous applications and clean some application caches?" --width 400 && init
			stop
		else
			echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is not running! Can't stop service!$RESETCOLOR\n" >&2
		fi
	;;
	changeid|change-id|change)
		checkuid
		change
	;;
	status)
		if [ "$(service anonsurfd status | grep Active | awk '{print $2}')" = "active" ]; then
			status
		else
			echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is not running!$RESETCOLOR\n"
		fi
	;;
	myip|ip)
		ip
	;;
	dns)
		dns
	;;
	restart)
		# Restart if the daemon is running onnly
		checkuid
		if [ "$(service anonsurfd status | grep Active | awk '{print $2}')" = "active" ]; then
			$0 stop
			sleep 1
			$0 start
		else
			echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is not running! Can't restart service!$RESETCOLOR\n" >&2
		fi
	;;
	enable-boot)
		checkuid
		enable-boot
	;;
	disable-boot)
		checkuid
		disable-boot
	;;
   *)
echo -e "
Parrot AnonSurf Module (v 2.11)

	Usage:
	$RED┌──[$GREEN$USER$YELLOW@$BLUE`hostname`$RED]─[$GREEN$PWD$RED]
	$RED└──╼ \$$GREEN"" anonsurf $RED{$GREEN""start$RED|$GREEN""stop$RED|$GREEN""restart$RED|$GREEN""enable-boot$RED|$GREEN""disable-boot$RED|$GREEN""change$RED""$RED|$GREEN""status$RED""}

	$RED start$BLUE -$GREEN Start system-wide TOR tunnel
	$RED stop$BLUE -$GREEN Stop anonsurf and return to clearnet
	$RED restart$BLUE -$GREEN Combines \"stop\" and \"start\" options
	$RED enable-boot$BLUE -$GREEN Enable AnonSurf at boot
	$RED disable-boot$BLUE -$GREEN Disable AnonSurf at boot
	$RED changeid$BLUE -$GREEN Restart TOR to change identity
	$RED status$BLUE -$GREEN Check if AnonSurf is working properly
	$RED myip$BLUE -$GREEN Check your ip and verify your tor connection
	$RED dns$BLUE -$GREEN Fast set / fix DNS. Please use /usr/bin/dnstool.
$RESETCOLOR
Dance like no one's watching. Encrypt like everyone is.
" >&2

exit 1
;;
esac

echo -e $RESETCOLOR
exit 0
